run:
  concurrency: 8
  deadline: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - staticcheck
    - unused
    - gosimple
    - govet
    - prealloc
    - unconvert
    - nakedret

linters-settings:
  govet:
    check-all: true
    enable:
      - fieldalignment