name: notify
on: [push]
jobs:
  notify:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://git.unistack.org/${{ github.repository }}/commit/${{github.sha}}