name: notify
on: [push]
jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - name: send
        uses: https://github.com/cbrgm/telegram-github-action@v1.2.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New commit by ${{ github.actor }}:
            Commit: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Changes: https://git.unistack.org/${{ github.repository }}/commit/${{github.sha}}